name: Deploy HTML to Server

on:
  push:
    branches:
      - main  # или ваша ветка

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Upload HTML file via SCP
      run: |
        scp -o StrictHostKeyChecking=no -r ./index.html rackir@195.138.69.40:/www/var/html
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}